version: "3.8"
services:
  my_portfolio:
    build:
      context: .
      dockerfile: dockerfile
    image: my_portfolio
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev